name: update-data
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install -r requirements.txt
          playwright install chromium

      - run: python crawlers/debug_naver_render.py
      - run: python crawlers/naver_parser.py

      - run: |
          git config user.name "bot"
          git config user.email "bot@test.com"
          git add .
          git commit -m "data update" || echo "no changes"
          git push
